- name: Install apt and flatpak
  hosts: my_local
  become: true # TODO: replace with individual become statements per task
  tasks:
    - name: Vim - install
      apt:
        name: vim
        state: present
    - name: Git - Install
      apt:
        name: git
        state: present
    - name: Github gh CLI - Install
      apt:
        name: gh
        state: present
    - name: Flatpak - install
      apt:
        name: flatpak
        state: present
    - name: Prusa Slicer - install
      apt:
        name: prusa-slicer
        state: present
    - name: FreeTube - install # Youtube alternative frontend
      community.general.flatpak:
        name: io.freetubeapp.FreeTube
        state: latest # always update
    - name: pip3 - install
      apt:
        name: python3-pip
        state: present
    - name: fzf - install
      apt:
        name: fzf
        state: present
    - name: RPI Imager - install
      apt:
        name: rpi-imager
        state: present
    - name: nmap - install
      apt:
        name: nmap
        state: present
    - name: sshpass - install
      apt:
        name: sshpass
        state: present
    - name: Okular - install
      apt:
        name: okular
        state: present
    - name: Chromium - install
      apt:
        name: chromium
        state: present
    - name: tmux - install
      apt:
        name: tmux
        state: present