# TODO: create .yml for the below
- name: Install scripts
  hosts: my_local
  become: true
  tasks: 
    # - name: Bun - check state
    #   shell: command -v bun
    #   register: bun_installed
    #   ignore_errors: yes
    # - name: Bun - install 
    #   shell: curl -fsSL https://bun.sh/install | bash
    #   environment: 
    #     HOME: "{{ ansible_env.HOME }}"
    #   when: bun_installed is failed
        # TODO: comment until state value is defined
    # - name: Volta - install
    #   # FIX: not working, script doesn't add vars to path,
    #   # Leaving task as install docs
    #   shell: curl https://get.volta.sh | bash
    # TODO: comment out because it's missing a state value
    # - name: autocpu-freq - Download
    #   ansible.builtin.git:
    #     repo: https://github.com/AdnanHodzic/auto-cpufreq.git
    #     dest: /home/nf/auto-cpufreq
    #     clone: yes
    #     update: no
    #     single_branch: yes
    #     version: master
    # TODO: not working correctly
    #  - name: autocpu-freq - Install
    #    ansible.builtin.command:
    #     cmd: ./auto-cpufreq-installer
    #    become: yes
    #    args:
    #      chdir: /home/nf/auto-cpufreq
    #    responses:
    #     'Select a key [I]nstall/[R]emove or press ctrl+c to quit:': 'I'
    #    echo: yes
